name: Pervaziv AI Code Review
description: AI Code review with full repo security results in GitHub Actions & Security tabs, and detailed report in Pervaziv AI console
branding:
  icon: 'shield'
  color: 'black'
author: 'Pervaziv AI'
inputs:
  backend-url:
    description: Pervaziv AI backend URL
    required: false
    default: 'https://console.pervaziv.com:8443/handleGitAction'
  console-url:
    description: Pervaziv AI console URL
    required: false
    default: 'https://console.pervaziv.com'

runs:
  using: node20
  main: dist/index.js
